"""add_priority_to_jobs

Revision ID: 46fa685ef10c
Revises: 64e076bbe121
Create Date: 2026-03-19 12:19:20.375724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fa685ef10c'
down_revision: Union[str, Sequence[str], None] = '64e076bbe121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('jobs', sa.Column('priority', sa.Integer(), nullable=True))
    op.execute("UPDATE jobs SET priority = 5 WHERE priority IS NULL")
    op.alter_column('jobs', 'priority', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'priority')
    # ### end Alembic commands ###
